### ISSUE TITLE
Extension fails to load with `refeclaration of let fact` on GNOME Shell 3.28 (GJS 1.52)

### ISSUE THREAD

**Issue by gergelypolonkai** [projecthamster/shell-extension#281]
I just tried to install the extension and, according to `lg`, it fails with `SyntaxError: redeclaration of let fact`.

PR is on the way.

**Comment by gergelypolonkai** [comment]
My bad… the problem is already solved by c36d5cae31579910a6cd5b02e99282e1c00d0cc5, but seems to be unreleased.

**Comment by ruedigerkupper** [comment]
Same problem here in Ubuntu 18.04 Bionic Beaver (GNOME 3.28.1).
That's particularly bad, since the update process removed the (well working) hamster-indicator. I need hamster time tracker on a daily basis, please fix!
Thank you!

**Comment by elbenfreund** [comment]
@ruedigerkupper Hi, i assume you are using an older version of `gnome-shell-extension`.
Please try the most reacent version from `develop` as per README and let us know your restults.

About the release:
Technically version `0.10.0` has been released already. However, in order to stick with gnome best practices we  *distribute* it only via [EOG](extensions.gnome.org). Unfortunately it is stull stuck in review over there... :( not much we can do about this.

Alternatively you can just checkout `develop` and run the convenient `dist` target provided as stated in the readme.

**Comment by ruedigerkupper** [comment]
Right, Version from github works -- I only had tried the one from extensions.gnome.org.

Note: I had to compile the main app from the sources, too. -- Hamster time tracker has been removed from Ubuntu's package repository with 18.04. Was that on purpose? Do you know anything about it?
The shell extension would never work without the main app, right? So Ubuntu users will not be able to use the shell extension either (without compiling).

**Comment by elbenfreund** [comment]
> Right, Version from github works -- I only had tried the one from extensions.gnome.org.

Glad to hear.

> Note: I had to compile the main app from the sources, too. -- Hamster time tracker has been removed from Ubuntu's package repository with 18.04. Was that on purpose? Do you know anything about it?
> The shell extension would never work without the main app, right? So Ubuntu users will not be able to use the shell extension either (without compiling).

That is correct. Packaging any software is done by the distribution's *maintainers*. This is not something the developer of a package necessarily does (often refered to as *upstream*).
So if ubuntu decides that it is no longer part of their distribution, thats someting independent of us and we can not really comment on this.

Sometimes, software developers may package their software themself to reduce the barrier of entry to a distribution or simply because they use the distribution themselfs. Or a member of the community offers to do so. Both is not the case for hamster right now as far as i can tell. We are however very much interested and welcoming to anyone wanting to help out.

the new hamster (`hamster-gtk`) is already available for *NIX-OS if I am not mistaken.

Punshline: as of now, there will most likekly be no hamster as part of ubuntu 18. if someone wants to build an unofficial community package that would be great thouhg.
Meanwhile, work on the new hamster is picking up again and we hope to have something ready for production during the later part of the year.

`

https://github.com/projecthamster/hamster/issues/356

**Comment by scalablockchain-dev** [comment]
I just tried to install the extension and, according to lg, it fails with SyntaxError: redeclaration of let fact.

OS : ubuntu 18.04

`SyntaxError: redeclaration of let renderer

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  `

**Comment by elbenfreund** [comment]
> I just tried to install the extension and, according to lg, it fails with SyntaxError: redeclaration of let fact.

Which version?
